allow_all_imports: true
apps:
  # charger:
  #   - battery: sensor.poco_f1_battery_level
  #     charging_state: binary_sensor.poco_f1_is_charging
  #     charger: switch.caricatore
  #     alarm_time: sensor.poco_f1_next_alarm
  #     day_start_time: '09:30:00'
  #     day_end_time: '23:00:00'