speed_test:
  alias: Speed Test
  sequence:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
      - sensor.speedtest_ping
      - sensor.speedtest_download
      - sensor.speedtest_upload
  mode: single
  icon: mdi:speedometer
reaload_automation:
  alias: Reaload Automation
  sequence:
  - service: automation.reload
    data: {}
  mode: single
  icon: mdi:reload-alert
turn_on_tv_samsung:
  alias: Turn On TV Samsung
  sequence:
  - service: media_player.turn_on
    data: {}
    target:
      entity_id: media_player.samsung_tv
  mode: single
  icon: mdi:television
request_location_update_mobile_apps:
  alias: Request Location Update - Mobile Apps
  sequence:
  - service: notify.mobile_app_poco_f1
    data:
      message: request_location_update
  - service: notify.mobile_app_sm_a525f
    data:
      message: request_location_update
  - service: notify.mobile_app_sm_m307fn
    data:
      message: request_location_update
  mode: single
  icon: mdi:google-maps
toggle_for_area_lights:
  alias: Toggle for area of lights
  fields:
    area_id:
      name: Area
      description: Area where to toggle lights
      required: true
      selector:
        area:
          entity:
            domain: light
  sequence:
    - if:
        - condition: template
          value_template: >-
            {{ (area_entities(area_id) | select('match', 'light.*') |
            select('is_state', 'on') | list | count ) > 0 }}
      then:
        - service: light.turn_off
          target:
            area_id: "{{ area_id }}"
          data: {}
      else:
        - service: light.turn_on
          target:
            area_id: "{{ area_id }}"
          data: {}

