# secrets file needed to run the containers; use 'docker compose --env-file <path-to-secret-env-file> up -d' to run
version: "3.9"

services:
  
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    environment:
      TZ: $TIMEZONE
    network_mode: host
    volumes:
      - $BASE_FOLDER/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
  # https://www.home-assistant.io/installation/alternative#docker-compose

  deconz:
    container_name: deconz
    image: deconzcommunity/deconz
    volumes:
      - $BASE_FOLDER/deconz:/opt/deCONZ
    devices:
      - /dev/ttyACM0
    environment:
      TZ: $TIMEZONE
      DECONZ_WEB_PORT: $DECONZ_WEB_PORT
      DECONZ_VNC_MODE: "1"
      DECONZ_VNC_PORT: $DECONZ_VNC_PORT
      DECONZ_VNC_PASSWORD: $DECONZ_VNC_PWD
    network_mode: host
    restart: unless-stopped
    privileged: true
  # https://github.com/deconz-community/deconz-docker

  caddy:
    container_name: caddy
    # image: caddy:latest
    build:
      context: .
      dockerfile_inline: |
        FROM caddy:builder AS builder

        RUN xcaddy build \
          --with github.com/caddy-dns/duckdns

        FROM caddy:latest

        COPY --from=builder /usr/bin/caddy /usr/bin/caddy
    environment:
      TZ: $TIMEZONE
      EXTERNAL_HASSIO_URL: $EXTERNAL_HASSIO_URL
      EXTERNAL_HASSIO_PORT: $EXTERNAL_HASSIO_PORT
      DUCK_DNS_TOKEN: $DUCK_DNS_TOKEN
      HOST_ADDRESS: $HOST_ADDRESS
      LOCAL_HASSIO_PORT: $LOCAL_HASSIO_PORT
    ports:
      - "446:446"
      - "80:80"
    volumes:
      - "$BASE_FOLDER/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "$BASE_FOLDER/caddy/data:/data"
    restart: unless-stopped
  # https://hub.docker.com/_/caddy
    

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: $TIMEZONE
      WEBPASSWORD: $DECONZ_PIHOLE_PWD #'set a secure password here or it will be random'
      WEB_PORT: $PIHOLE_WEB_PORT
      FTLCONF_REPLY_ADDR4: $HOST_ADDRESS
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "$PIHOLE_WEB_PORT:$PIHOLE_WEB_PORT/tcp"
    volumes:
      - "$BASE_FOLDER/pihole/etc-pihole:/etc/pihole"
      - "$BASE_FOLDER/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
      - type: bind
        source: $BASE_FOLDER/pihole/lighttpd/external.conf
        target: /etc/lighttpd/external.conf
      - "$BASE_FOLDER/pihole/backups:/backups"
    # cap_add:
    # - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
  # https://github.com/pi-hole/docker-pi-hole
