blueprint:
  name: FIX - Do Not Deactivate - Zigbee Ikea Lights fix
  description: fix the random turn on of lights (you will need an input_boolean for each lights you want to fix)
  domain: automation
  author: bit00
  # homeassistant:
  #   min_version:
  input:
    ikea_light_entity:
      name: Ikea Light Entity
      description: the light entity of the ikea light that randomly turns on
      selector:
        entity:
          filter:
            domain: light
      # default:
    input_boolean:
      name: input_boolean
      description: the created input_boolean needed for the automation (To add one, go to Settings > Devices & Services > Helpers and click the add button; next choose the Toggle option. Another options is to add it on the configuration.yaml file under input_boolean:)
      selector:
        entity:
          filter:
            domain: input_boolean

mode: parallel
max: 100
max_exceeded: warning

trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: light
      service: turn_on
      service_data:
        entity_id: !input ikea_light_entity
    id: "call_on"
  - platform: event
    event_type: call_service
    event_data:
      domain: light
      service: turn_off
      service_data:
        entity_id: !input ikea_light_entity
    id: "call_off"
  - platform: event
    event_type: call_service
    event_data:
      domain: light
      service: toggle
      service_data:
        entity_id: !input ikea_light_entity
    id: "toggle"
  # - platform: state
  #   entity_id:
  #     - !input ikea_light_entity
  #   to: "on"
  #   id: "on"
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: !input ikea_light_entity
      new_state:
        state: "on"
      old_state:
        state: "off"
    id: "on"
  # - platform: state
  #   entity_id:
  #     - !input ikea_light_entity
  #   to: "off"
  #   id: "off"
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: !input ikea_light_entity
      new_state:
        state: "off"
      old_state:
        state: "on"
    id: "off"
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - call_on
        sequence:
          - service: input_boolean.turn_on
            metadata: {}
            data: {}
            target:
              entity_id: !input input_boolean
      - conditions:
          - condition: trigger
            id:
              - call_off
        sequence:
          - service: input_boolean.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: !input input_boolean
      - conditions:
          - condition: trigger
            id:
              - toggle
        sequence:
          - service: input_boolean.toggle
            metadata: {}
            data: {}
            target:
              entity_id: !input input_boolean
      - conditions:
          - condition: trigger
            id:
              - "on"
        sequence:
          - delay:
              hours: 0
              minutes: 0
              seconds: 1
              milliseconds: 0
          - if:
              - condition: state
                entity_id: !input input_boolean
                state: "off"
            then:
              - service: light.turn_off
                metadata: {}
                data: {}
                target:
                  entity_id: !input ikea_light_entity
      - conditions:
          - condition: trigger
            id:
              - "off"
        sequence:
          - service: input_boolean.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: !input input_boolean
